
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN Y19 [get_ports sys_rst_n]
set_property PACKAGE_PIN W19 [get_ports sys_clk]



set_property PACKAGE_PIN F18 [get_ports {tmds_data_p[2]}]
set_property PACKAGE_PIN B15 [get_ports {tmds_data_p[1]}]
set_property PACKAGE_PIN E16 [get_ports {tmds_data_p[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ddc_scl]
set_property IOSTANDARD LVCMOS33 [get_ports ddc_sda]
set_property PACKAGE_PIN A13 [get_ports tmds_clk_p]
set_property PACKAGE_PIN D14 [get_ports ddc_scl]
set_property PACKAGE_PIN E14 [get_ports ddc_sda]
set_property IOSTANDARD TMDS_33 [get_ports tmds_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p[0]}]


#数码管
set_property PACKAGE_PIN K18 [get_ports {sel[5]}]
set_property PACKAGE_PIN K16 [get_ports {sel[4]}]
set_property PACKAGE_PIN L16 [get_ports {sel[3]}]
set_property PACKAGE_PIN G20 [get_ports {sel[2]}]
set_property PACKAGE_PIN H20 [get_ports {sel[1]}]
set_property PACKAGE_PIN H18 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]

set_property PACKAGE_PIN U22  [get_ports {seg[0]}]
set_property PACKAGE_PIN P19  [get_ports {seg[1]}]
set_property PACKAGE_PIN W21  [get_ports {seg[2]}]
set_property PACKAGE_PIN V22  [get_ports {seg[3]}]
set_property PACKAGE_PIN AB20 [get_ports {seg[4]}]
set_property PACKAGE_PIN W22  [get_ports {seg[5]}]
set_property PACKAGE_PIN AA20 [get_ports {seg[6]}]
set_property PACKAGE_PIN AA21 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]


#网口
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {eth_rxd[0]}]
set_property PACKAGE_PIN E21 [get_ports {eth_rxd[3]}]
set_property PACKAGE_PIN A21 [get_ports {eth_rxd[2]}]
set_property PACKAGE_PIN B21 [get_ports {eth_rxd[1]}]
set_property PACKAGE_PIN A20 [get_ports {eth_rxd[0]}]

set_property PACKAGE_PIN H14 [get_ports eth_rst_n]
set_property PACKAGE_PIN B20 [get_ports eth_rx_ctl]
set_property PACKAGE_PIN C18 [get_ports eth_rxc]
set_property PACKAGE_PIN W19 [get_ports sys_clk]
set_property PACKAGE_PIN Y19 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports eth_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property PACKAGE_PIN P20 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]

set_property PACKAGE_PIN R16 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports key]


set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]
set_property PACKAGE_PIN N20 [get_ports {led_out[0]}]
set_property PACKAGE_PIN M20 [get_ports {led_out[1]}]
set_property PACKAGE_PIN N22 [get_ports {led_out[2]}]
set_property PACKAGE_PIN M22 [get_ports {led_out[3]}]